apiVersion: v1
kind: Service
metadata:
  name: vnc-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: vncserver
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900
